/**:
  ros__parameters:
    chomp:
      group_name: iiwa_arm
      planner_configs:
        - CHOMPkConfigDefault

    CHOMPkConfigDefault:
      max_iterations: 1000
      max_iterations_after_collision_free: 5
      smoothness_cost_weight: 0.1
      obstacle_cost_weight: 1.0
      learning_rate: 0.01
      animate_path: true
      add_randomness: false
      smoothness_cost_velocity: 0.0
      smoothness_cost_acceleration: 1.0
      smoothness_cost_jerk: 0.0
      hmc_discretization: 0.01
      hmc_stochasticity: 0.01
      hmc_annealing_factor: 0.99
      use_hamiltonian_monte_carlo: false
      ridge_factor: 0.0
      enable_failure_recovery: true
      max_recovery_attempts: 5
      trajectory_initialization_method: "quintic-spline"
      use_stochastic_descent: true
